# Generated by Django 4.2.5 on 2023-10-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exceldata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.TextField()),
                ('genes', models.TextField()),
                ('genes_id', models.TextField()),
                ('variant', models.TextField()),
                ('chr', models.TextField()),
                ('ref_allle', models.TextField()),
                ('alt_allel', models.TextField()),
                ('af', models.TextField()),
                ('clinical_significance', models.TextField()),
            ],
        ),
    ]
