# Generated by Django 4.2.5 on 2023-10-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genesearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceldata',
            name='clinvar_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='variant_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
