# Generated by Django 4.1.12 on 2023-10-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genesearch', '0002_exceldata_clinvar_id_exceldata_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceldata',
            name='chr',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='clinical_significance',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='clinvar_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='disease',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='genes',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='genes_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='position',
            field=models.CharField(db_index=True, default=11, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='variant',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='variant_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
